### PR TITLE
Add redefinig-special-forms

### PR DESCRIPTION
**Pull request by jpellegrini**
This is different from "redefining syntax", as special forms may be more hardly encoded in implementations... :)

### CODE REVIEW

**Comment by jpellegrini** [comment]
I just realized there is also "redefining-keywords", but while it handles more Schemes, it also doesn't do as much a detail study as this one. Maybe merge...

**Comment by lassik** [comment]
Thanks a lot the continued effort on the surveys, and sorry about the lack of reviews! I've struggled to find time and energy for open source lately. I trust your judgment, so just merge whatever you think is good enough. And let me know if you want access to push to the server.

**Comment by jpellegrini** [comment]
* access to push to the server -- yes thank you. Do i sendo SN SSH público key?

**Comment by lassik** [comment]
Please check your email.

**Pull request merged**
